platform :ios, '7.0'
target 'music' do
 pod 'Reachability'
 pod 'UMengAnalytics'
 pod 'AFNetworking'
 pod 'MJExtension'
 pod 'BlocksKit'
 pod 'MBProgressHUD'
 pod 'SVProgressHUD'
 pod 'KVOController'
 pod 'SDWebImage'
 pod 'Mantle'
 pod 'MJRefresh'
 pod 'Masonry','~>1.0.2'
 pod 'WebViewJavascriptBridge'
 pod 'SDCycleScrollView'
 pod 'UITableView+FDTemplateLayoutCell'
 pod 'BmobSDK'
end

